### ISSUE TITLE
I suggest package it as a Docker image

### ISSUE THREAD

**Issue by stardiviner** [countstarlight/homo#1]
If this is provide as a Docker image would be better and simple to use. WDYT?

**Comment by vufa** [comment]
:wink:Agree, I am working on it.

**Comment by stardiviner** [comment]
Any update on this? Just ping..

**Comment by vufa** [comment]
Travis-ci is ready to work, :thinking: but I am considering that webview + x11 in docker may not be a good solution.
:star2:The x11 docker image will be released in the next few days, and I plan to create a web server as the interface.

**Comment by stardiviner** [comment]
I see, a web server seems a good solution. Don't know whather Docker can work good for x11 application.

**Comment by linonetwo** [comment]
What does X11 mean, is that something likes electron? Maybe it can be run as a standalone app, and connect to the server running in the docker.

**Comment by vufa** [comment]
:tada: Docker image is ready: [快速开始(Linux)](https://github.com/countstarlight/homo#%E5%BF%AB%E9%80%9F%E5%BC%80%E5%A7%8Blinux)

**Comment by vufa** [comment]
> What does X11 mean, is that something likes electron? Maybe it can be run as a standalone app, and connect to the server running in the docker.

The docker container will connect to the host's X11 server and share hardware(audio, etc.) with the host, the same as the native application. :satisfied: As I said before, I plan to create a web server as the interface.
